// Mock data for the prototype.

const SAMPLE_PROJECTS = [
  {
    id: "09-sms-modem",
    name: "09 — SMS Modem",
    mcu: "STM32H573",
    status: "build-clean",
    statusLabel: "Build clean · flash pending",
    summary: "Quectel EG915N SMS + TCP socket via UART2 with CTS/RTS.",
    lastRun: "2 hours ago",
    iterations: 12,
    files: 47,
  },
  {
    id: "07-dual-blink",
    name: "07 — Dual Blink",
    mcu: "STM32H573",
    status: "build-clean",
    statusLabel: "Build clean",
    summary: "Two LEDs blinking at independent rates via TIM2 / TIM3.",
    lastRun: "yesterday",
    iterations: 4,
    files: 22,
  },
  {
    id: "04-gsensor",
    name: "04 — G-Sensor",
    mcu: "STM32H573",
    status: "verified",
    statusLabel: "Verified on hardware",
    summary: "LSM6DSO accelerometer over SPI4 — canonical reference project.",
    lastRun: "3 days ago",
    iterations: 8,
    files: 31,
  },
  {
    id: "ThreadX",
    name: "ThreadX",
    mcu: "STM32H573",
    status: "verified",
    statusLabel: "Verified on hardware",
    summary: "Azure RTOS blink — tx_timer + dedicated thread.",
    lastRun: "1 week ago",
    iterations: 5,
    files: 38,
  },
  {
    id: "05-psram",
    name: "05 — PSRAM",
    mcu: "STM32H573",
    status: "verified",
    statusLabel: "Verified on hardware",
    summary: "ISSI 66/67WVS16M8 PSRAM via OctoSPI.",
    lastRun: "2 weeks ago",
    iterations: 6,
    files: 19,
  },
  {
    id: "03-gsensor",
    name: "03 — G-Sensor (legacy)",
    mcu: "STM32H573",
    status: "verified",
    statusLabel: "Verified on hardware",
    summary: "Earlier LSM6DSO driver iteration.",
    lastRun: "3 weeks ago",
    iterations: 9,
    files: 28,
  },
];

// A scripted run that the prototype replays in the trace pane.
const SAMPLE_RUN = [
  { kind: "session", time: "14:02:11", text: "Session started · model: claude-sonnet-4-5 · effort: max" },
  { kind: "meta", time: "14:02:11", text: "Workspace: ~/DirectClaude  ·  Continue: 09-sms-modem  (auto-detected)" },
  { kind: "meta", time: "14:02:11", text: "Skills: 4  [stm32, modem, embedded-general/coding, embedded-general/testing]" },
  { kind: "meta", time: "14:02:11", text: "Prefix: ~8,420 tokens  ·  Max iters: 10" },
  { kind: "text", time: "14:02:14", text: "Resuming SMS modem project. STATE.md says build is clean and the next step is to flash and verify the trace shows EG915N power-on sequence. Reading STATE.md and main app source first." },
  { kind: "tool", time: "14:02:15", name: "Read", arg: "projects/09-sms-modem/STATE.md" },
  { kind: "result", time: "14:02:15", text: "## Status\nBuild clean. SMS send/receive logic implemented. CTS/RTS handshake working in unit tests." },
  { kind: "tool", time: "14:02:17", name: "Read", arg: "projects/09-sms-modem/Core/Src/app_modem.c" },
  { kind: "result", time: "14:02:17", text: "365 lines · last modified 2h ago" },
  { kind: "text", time: "14:02:21", text: "Code looks consistent with the EG915N AT command reference. Going to build, flash, and capture trace from COM7." },
  { kind: "tool", time: "14:02:22", name: "Bash", arg: "cmake --build build --target TFL_CONNECT_2 -j" },
  { kind: "result", time: "14:02:38", text: "[100%] Built target TFL_CONNECT_2.elf · 38.4 KB FLASH · 12.1 KB SRAM" },
  { kind: "confirm", time: "14:02:39", title: "Flash to hardware?", detail: "Programmer will write 38.4 KB to STM32H573VIT3Q via ST-LINK on SWD @ 4 MHz, then issue hardware reset.", danger: false, command: "STM32_Programmer_CLI -c port=SWD freq=4000 -w build/TFL_CONNECT_2.elf -rst" },
  { kind: "tool", time: "14:02:51", name: "Bash", arg: "STM32_Programmer_CLI -l st" },
  { kind: "result", time: "14:02:52", text: "ST-LINK SN: 002C00343338510034313939  ·  Probe found" },
  { kind: "tool", time: "14:02:53", name: "Bash", arg: "STM32_Programmer_CLI -c port=SWD freq=4000 -w build/TFL_CONNECT_2.elf -rst" },
  { kind: "result", time: "14:03:02", text: "Memory programmed in 7.2 s · Verify OK · MCU reset" },
  { kind: "text", time: "14:03:04", text: "Opening COM7 @ 115200 8N1 to read the trace before issuing soft reset." },
  { kind: "tool", time: "14:03:05", name: "Bash", arg: "python tools/trace.py --port COM7 --baud 115200 --timeout 12" },
  { kind: "result", time: "14:03:17", text: "[BOOT] H573 cold start  SYSCLK=250 MHz\n[MODEM] PWR pin -> HIGH\n[MODEM] PWRKEY pulse 1100 ms\n[MODEM] URC: RDY\n[MODEM] AT echo OK\n[MODEM] CPIN: READY\n[MODEM] CSQ: 22,99\n[APP] ready — type | sendsms <num> <msg>" },
  { kind: "fix", time: "14:03:19", text: "Trace matches expected boot sequence. Updating STATE.md to mark project as flashed-and-verified." },
  { kind: "tool", time: "14:03:20", name: "Edit", arg: "projects/09-sms-modem/STATE.md" },
  { kind: "result", time: "14:03:20", text: "Status: Verified on hardware · Next step: regression test (send-receive round trip)" },
  { kind: "success", time: "14:03:21", text: "Done · 11 turns · cost $0.184" },
];

window.SAMPLE_PROJECTS = SAMPLE_PROJECTS;
window.SAMPLE_RUN = SAMPLE_RUN;
